name: DevelopmentTests
#  Triggers the workflow on scheduled branch for the specified cron value
on:
  schedule:
    - cron:  '0 12-23 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
       ref: scheduled
   
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
